### PR TITLE
Continuous callback tests

### PR DESCRIPTION
**Pull request by korsbo**
A first pass at writing tests designed to catch errors like #37. 

The list of algorithms for which the test is performed should  be revised, do you have a list like that lying around?

### CODE REVIEW

**Comment by korsbo** [comment]
Note that the failed CI is due to the tests actually finding the errors that it was defined to find.

**Comment by ChrisRackauckas** [comment]
This should be in OrdinaryDiffEq.jl as an interface test and doesn't need DiffEqCallbacks.jl

>The list of algorithms for which the test is performed should be revised, do you have a list like that lying around?

No, it's just the methods with a special interpolation and it's documented but not as a nice list.

**Comment by korsbo** [comment]
Would this have caught Interpolation errors without callbacks making them visible? I never noticed interpolation errors with the Rosenbrock algorithms except for with callbacks.

**Comment by ChrisRackauckas** [comment]
The issue is the reconstruction of the derivatives after a pullback for special interpolants, so it would only show up on specific algorithms and only with a continuous callback. Rodas4/Rodas42 should be the only ones left that error, and that already has an open issue in OrdinaryDiffEq.jl. But we don't have a test for this exact case, so it's good to get a test going.

**Comment by korsbo** [comment]
Ok, but then I actually have to figure out how the pullback works. With my current project-juggling, that may have to wait a bit.

**Comment by ChrisRackauckas** [comment]
No worries. If you could move the PR over to OrdinaryDiffEq.jl I can take it from there.

**Comment by korsbo** [comment]
Moved (as is) to OrdinaryDiffEq.jl. Closing.

**Pull request closed without merging**
